timeUpdate: 10 #Раз во сколько тиков обновлять возможность стройки? (20 тиков = 1 секунда) [Default: 10]

allowClickItems: #Какими предметами можно кликать во всех приватах?
- bread:0

allowBreakBlocks: #Какие блоки можно ломать во всех приватах (WG защита будет проигнорирована!)?
- gravestone_gravestone:*

enabled: true #Если true - вывод включен, если false - выключен

denyFormat: '[&4{REGION}&f]' #Формат вывода названия привата, к которому нет доступа на экран. [Default: '[&4{REGION}&f]']

allowFormat: '[&a{REGION}&f]' #Формат вывода названия привата, к которому есть доступ на экран. [Default: '[&a{REGION}&f]']

emptyFormat: '[&eGLOBAL&f]' #Что вывести если регионов нет? Установите '', если не хотите ничего выводить на экран [Default: '[&eGLOBAL&f]']

displayOneRegion: true #Если true - выводит только самый приоритетный регион, если false - все регионы, на которые смотрит игрок

displayType: DEFAULT #Режим вывода информации. Доступно: USER, DEFAULT. USER - выводит владельца региона, DEFAULT - название региона

X: 10 #Координаты места на экране, где будет выведено название региона
Y: 10 #Координаты места на экране, где будет выведено название региона

permission: worldguard.tweaks.info #Пермишен, который требуется для получения названий регионов